### ISSUE TITLE
数据集太小会报错

### ISSUE THREAD

**Issue by bleachbeauty** [xhw205/GlobalPointer_torch#7]

**Comment by xhw205** [comment]
这一句 `f1, precision, recall = 2 * X / (Y + Z), X / Y, X / Z` 计算F1时候，遇到除0的情况了。
可以判断下若 Y, Z 为 0，就赋值为 1e-10。
是因为数据集一个batch里的 set(true) 为空导致的。

**Comment by bleachbeauty** [comment]
感谢您的指教，经测试，已经可以跑通了。
另外1e-10的设置是固定的嘛？可以有其他调整的方案嘛？
最后，不知可否加QQ或者微信交流一下，感谢您的回复。
QQ：742489735
敬颂安康




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xhw205/GlobalPointer_torch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月10日(星期五) 晚上11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xhw205/GlobalPointer_torch] 数据集太小会报错 (Issue #7)





 
这一句 f1, precision, recall = 2 * X / (Y + Z), X / Y, X / Z 计算F1时候，遇到0的情况了。
 可以判断下若 Y, Z 为 0，就赋值为 1e-10。
 是因为数据集一个batch里的 set(true) 为空导致的。
